---
title: "Assingment NYC Flight Data"
author: "Vani P Jyothy"
date: "April 9 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## NYC Flight Data

Your job is to create a "rectangular" table useful for modeling from flight data. 
In the folder `02-fundamentals/data` there are four CSV files: `flights.csv`, 
`airports.csv`, `planes.csv` and `weather.csv`.  Join/merge these tables such 
that there is one rectangular table with one row for each flight. 


Put code in each of the sections provided.

## 1. Read Data

Using the `readr` package read the `flights` data.

```{
flights=read.csv("C:\\Users\\Vani\\Downloads\\UCB\\CSX460\\02-building-blocks\\02-exercise-nycflights\\ata\\flights.csv")

}

```

## Numeric Variables  

Plot a histogram of arrival delays and departure delays 

```{
# hist of arrival Delay

hist(flights$arr_delay, 
     main="Histogram for Arrival Delay", 
     xlab="Arrival delay", 
     border="blue", 
     col="green",
     xlim=c(-100,700),
     las=1, 
     breaks=5)

# Hist of Dept Delay

   hist(flights$dep_delay, 
     main="Histogram for Departure Delay", 
     xlab="Departure delay", 
     border="blue", 
     col="pink",
     xlim=c(-200,700),
     las=1, 
     breaks=5) 
     }

```

## Scatterplot

Plot a scatterplot of date vs arrival delay 

```{
##Adding a date variable by concatinationg year,month&Day


flights$date <- as.Date(with(flights, paste(year, month, day,sep="-")), "%Y-%m-%d")

##Plotting date vs arrival delay

plot(flights$date,flights$arr_delay,main = "Scatter plot of date vs arrival delay",xlab = "Date", ylab = "Arrival Delay")
}

```



## Create tables for Categorical Variables

Create a `table`, counting the flights by origin airports and carrier.

```{
flights_dt=data.table(flights)
flights_by_orig_carr=flights_dt[,.(count=.N),by=.(carrier,origin)]
}
...

## Join Data

**Read** in the other data sets. Use methods to join the data together to create a single table containing one record per row.  (HINT: see `?data.table` or `?dplyr::join`)

```{

#reading the AIRPORT dataset

airports=read.csv("C:\\Users\\Vani\\Downloads\\UCB\\CSX460\\02-building-blocks\\02-exercise-nycflights\\data\\airports.csv")

#storing the data in to datatable

airports_dt=data.table(airports)

#Reading the PLANES data set

planes=read.csv("C:\\Users\\Vani\\Downloads\\UCB\\CSX460\\02-building-blocks\\02-exercise-nycflights\\data\\planes.csv")
#storing the data in to datatable
planes_dt=data.table(planes)

#reading the WEATHER dataset
weather=read.csv("C:\\Users\\Vani\\Downloads\\UCB\\CSX460\\02-building-blocks\\02-exercise-nycflights\\data\\weather.csv")

#storing the data in to datatable
weather_dt=data.table(weather)

#Joining to make a single data table

Aviation=left_join(flights_dt,airports_dt,by=c("origin"="faa")) %>% left_join(planes_dt) %>% left_join(weather_dt)
}

```



